name: Generate Snake

on:
  schedule:
    # Jalankan setiap hari pada jam 00:00 UTC
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository content
        uses: actions/checkout@v2

      - name: Generate Snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: nizarmahi
          svg_out_path: dist/output.svg

      - name: Upload Snake animation
        uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: dist/output.svg
